hotel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from accounts import views

from django.contrib.auth import views as auth_views


router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('home/', TemplateView.as_view(template_name='userinterfacedesign/index.html'), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('inventory/', include('inventory.urls', namespace='inventory')),
   


    path('pp/', include('supplier.urls'), name='procurement_portal'),

    ####### API #############################
    # path('', include(router.urls)),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.urls import path, include
from . import views

app_name = 'inventory'

urlpatterns = [
    ######################################################################################################
    path('products/', views.ProductsListView.as_view(), name='products_list'),
    path('products/new/', views.ProductsCreateView.as_view(), name='products_new'),
    path('products/detail/<int:pk>/', views.ProductsDetailView.as_view(), name='products_detail'),
    path('products/update/<int:pk>/', views.ProductsUpdateView.as_view(), name='products_update'),
    path('products/delete/<int:pk>/', views.ProductsDeleteView.as_view(), name='products_delete'),
    ##############################################################################################################3
    
      ######################################################################################################
    path('warehouse/', views.WarehouseListView.as_view(), name='warehouse_list'),
    path('warehouse/new/', views.WarehouseCreateView.as_view(), name='warehouse_new'),
    path('warehouse/detail/<int:pk>/', views.WarehouseDetailView.as_view(), name='warehouse_detail'),
    path('warehouse/update/<int:pk>/', views.WarehouseUpdateView.as_view(), name='warehouse_update'),
    path('warehouse/delete/<int:pk>/', views.WarehouseDeleteView.as_view(), name='warehouse_delete'),
    ##############################################################################################################3
      ######################################################################################################
    path('category/', views.CategoryListView.as_view(), name='category_list'),
    path('category/new/', views.CategoryCreateView.as_view(), name='category_new'),
    path('category/detail/<int:pk>/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('category/update/<int:pk>/', views.CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', views.CategoryDeleteView.as_view(), name='category_delete'),
    ##############################################################################################################3
      ######################################################################################################
    path('pallet/', views.PalletListView.as_view(), name='pallet_list'),
    path('pallet/new/', views.PalletCreateView.as_view(), name='pallet_new'),
    path('pallet/detail/<int:pk>/', views.PalletDetailView.as_view(), name='pallet_detail'),
    path('pallet/update/<int:pk>/', views.PalletUpdateView.as_view(), name='pallet_update'),
    path('pallet/delete/<int:pk>/', views.PalletDeleteView.as_view(), name='pallet_delete'),
    ##############################################################################################################3
    ##############################################################################################################
    path('batch/', views.BatchListView.as_view(), name='batch_list'),
    path('batch/new/', views.BatchCreateView.as_view(), name='batch_new'),
    ##############################################################################################################
    path('transaction/', views.TransactionListView.as_view(), name='transaction_list'),
    path('transaction/new/', views.transaction_create_view, name='transaction_new'),
  ]

inventory/models.py
from django.db import models
from accounts.models import User
# Create your models here.

class Category(models.Model):
    name = models.CharField(unique=True, max_length=50)
    description = models.TextField(default='New Category')
    
    def __str__(self):
        return self.name
    
class Warehouse(models.Model):
    name = models.CharField(unique=True, max_length=50)
    location = models.CharField(max_length=50)
    address =  models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    

class Pallet(models.Model):
    name = models.CharField(max_length=50)
    warehouse = models.ForeignKey(Warehouse, related_name='pallet', on_delete=models.CASCADE)
    description = models.CharField(max_length=250, null=True)
    
    class Meta:
        unique_together = ('name', 'warehouse')
        
    def __str__(self):
        return self.name
        
        
class Products(models.Model):

    UNIT_CHOICES = (
        ('Kilograms', 'Kilograms'),
        ('Liters', 'Liters'),
        ('Meters', 'Meters'),
        ('Piece', 'Piece'),
        ('Tonne', 'Tonne'),


    )
    VED_TYPE = (
        ('Vital', 'Vital'),
        ('Essential', 'Essential'),
        ('Desirable', 'Desirable'),



    )
    INVENTORY_TYPE = (
        ('Vital', 'Vital'),
        ('Essential', 'Essential'),
        ('Desirable', 'Desirable'),

    )
    MB_TYPE= (
        ('make', 'Make'),
        ('buy', 'Buy'),


    )
    name = models.CharField(max_length=255, unique=True)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    pallet = models.ForeignKey(Pallet, related_name='products', on_delete=models.CASCADE)

    VED_analysis = unit_measure = models.CharField(max_length=20, null=False,default='', choices=VED_TYPE)
    buy_or_make=unit_measure = models.CharField(max_length=20, null=False,default='', choices=MB_TYPE)
    selling_price = models.PositiveIntegerField(null=True)
    cost_price = models.PositiveIntegerField(null=True)
    selling_price = models.PositiveIntegerField()
    cost_price = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    quantity_available = models.PositiveIntegerField(null=True)
    unit_measure = models.CharField(max_length=20, null=False, choices=UNIT_CHOICES)
    ABC_category= models.CharField(max_length=2,null=True)
    FSN_analysis= models.CharField(max_length=255,null=True)
    reoder_level = models.PositiveIntegerField(default='')
    safety_stock_level = models.PositiveIntegerField(default=0)
    


    reoder_level = models.PositiveIntegerField()
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    pallet = models.ForeignKey(Pallet, related_name='products', on_delete=models.CASCADE)
    item_description = models.TextField( default='')
    def __str__(self):
        return self.name
        




class Batch(models.Model):
    STATE_CHOICES = (
    ('Finished', 'Finished'),
    ('Current', 'Current'),
    ('Later', 'Later'),)

    date_delivery = models.DateField(auto_now_add=True)
    date_expiry = models.DateField()
    date_finished = models.DateField()
    delivered_quantity = models.IntegerField()
    quantity_remaining = models.IntegerField()
    pallet = models.ForeignKey(Pallet, related_name='batch', on_delete=models.CASCADE)
    product = models.ForeignKey(Products, related_name='batch', on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name='batch', on_delete=models.CASCADE)
    supplier = models.ForeignKey('supplier.Company', related_name='batch', on_delete=models.CASCADE)
    state = models.CharField(max_length=20, default='Later', choices=STATE_CHOICES)
    def BatchNO(self):
        return str(self.pk) + '/' + str(self.supplier.user)+ '/' +str(self.receiver) 

    def __str__(self):
        batchno = self.BatchNO()
        return batchno

class Transaction(models.Model):
    product = models.ForeignKey(Products, related_name='transaction', on_delete=(models.CASCADE))
    date = models.DateField(auto_now_add=True)
    batch = models.ForeignKey(Batch, related_name='transaction', on_delete=(models.CASCADE))
    quantity = models.PositiveIntegerField()
    sold_by = models.ForeignKey(User, related_name='transaction', on_delete=(models.CASCADE))
    price = models.PositiveIntegerField()

    def __str__(self):
        return self.pk

inventory/forms.py
from django.forms import ModelForm, TextInput, NumberInput, DateField, SelectDateWidget
from .models import Products, Category, Warehouse, Pallet, Batch, Transaction

class ProductsForm(ModelForm):

    class Meta():
        model = Products
        fields = '__all__'
        exclude = ['quantity_available']   
        widgets = {
            'name': TextInput(attrs={'placeholder': "John Doe", "class": "form-control"}),
            'selling_price': NumberInput(attrs={"class": "form-control"}),

            'cost_price': NumberInput(attrs={"class": "form-control"}),

            'quantity': NumberInput(attrs={"class": "form-control"}),

            'quantity_available': NumberInput(attrs={"class": "form-control"}),
            'unit_measure': TextInput(attrs={"class": "form-control"}),

            'reoder_level': NumberInput(attrs={"class": "form-control"}),
            'category': TextInput(attrs={"class": "form-control"}),
        'assigned to': TextInput(attrs={"class": "form-control"}),
            'pallet': TextInput(attrs={"class": "form-control"}),



        }   



        

class CategoryForm(ModelForm):

    class Meta():
        model = Category
        fields = '__all__'
        
class WarehouseForm(ModelForm):

    class Meta():
        model = Warehouse
        fields = '__all__'
        
        
class PalletForm(ModelForm):

    class Meta():
        model = Pallet
        fields = '__all__'



class BatchForm(ModelForm):



    class Meta():
        model = Batch
        fields = '__all__'
        widgets = {
            'date_delivery': SelectDateWidget(),
            'date_expiry': SelectDateWidget(),
            'date_finished': SelectDateWidget(),

             
             } 


class TransactionForm(ModelForm):

    class Meta():
        model = Transaction
        fields = '__all__'
        widgets = {
            'date': SelectDateWidget(),

            }

inventory/views.py
from .forms import ProductsForm, CategoryForm, WarehouseForm, PalletForm, BatchForm, TransactionForm
from .models import Products, Warehouse, Category, Pallet, Batch, Transaction
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from django import template
from django.contrib.auth.models import Group

register = template.Library()




class ProductsCreateView(LoginRequiredMixin, CreateView):
    model = Products
    form_class = ProductsForm
    success_url = reverse_lazy('inventory:products_list')


class ProductsDetailView(LoginRequiredMixin, DetailView):
    model = Products


class ProductsUpdateView(LoginRequiredMixin, UpdateView):
    model = Products
    form_class = ProductsForm
    template_name_suffix = '_update_form'
    


class ProductsDeleteView(LoginRequiredMixin, DeleteView):
    model = Products
    success_url = reverse_lazy('management:employee_list')


class ProductsListView(LoginRequiredMixin, ListView):
    model = Products
    template_name = 'inventory/products_list.html'
    products = Products.objects.all()
    context = locals()
    context['products'] = products


    def get(self, request, *args, **kwargs):
        # form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'products': self.products})
    

    # print(products)

#######################################################################################

##############################################################################
# Category views


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('inventory:category_list')


class CategoryDetailView(LoginRequiredMixin, DetailView):
    model = Category


class CategoryUpdateView(LoginRequiredMixin, UpdateView):
    model = Category
    form_class = CategoryForm
    template_name_suffix = '_update_form'


class CategoryDeleteView(LoginRequiredMixin, DeleteView):
    model = Category
    success_url = reverse_lazy('management:employee_list')


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category

#######################################################################################

##############################################################################
# Warehouse views


class WarehouseCreateView(LoginRequiredMixin, CreateView):
    model = Warehouse
    form_class = WarehouseForm
    success_url = reverse_lazy('inventory:warehouse_list')


class WarehouseDetailView(LoginRequiredMixin, DetailView):
    model = Warehouse


class WarehouseUpdateView(LoginRequiredMixin, UpdateView):
    model = Warehouse
    form_class = WarehouseForm
    template_name_suffix = '_update_form'


class WarehouseDeleteView(LoginRequiredMixin, DeleteView):
    model = Warehouse
    success_url = reverse_lazy('management:employee_list')


class WarehouseListView(LoginRequiredMixin, ListView):
    model = Warehouse

#######################################################################################

##############################################################################
# Pallet views


class PalletCreateView(LoginRequiredMixin, CreateView):
    model = Pallet
    form_class = PalletForm
    success_url = reverse_lazy('inventory:pallet_list')


class PalletDetailView(LoginRequiredMixin, DetailView):
    model = Pallet


class PalletUpdateView(LoginRequiredMixin, UpdateView):
    model = Pallet
    form_class = PalletForm
    template_name_suffix = '_update_form'


class PalletDeleteView(LoginRequiredMixin, DeleteView):
    model = Pallet
    success_url = reverse_lazy('management:employee_list')


class PalletListView(LoginRequiredMixin, ListView):
    model = Pallet

#######################################################################################

class BatchCreateView(LoginRequiredMixin, CreateView):
    model = Batch
    form_class = BatchForm
    success_url = reverse_lazy('inventory:batch_list')


class BatchListView(LoginRequiredMixin, ListView):
    model = Batch


def transaction_create_view(request):
    template = 'inventory/transaction_form.html'
    if request.method == 'POST':
        form = TransactionForm()
        if form.is_valid():
            #create transaction
            transaction = form.save(commit=False)
            transaction.save()
            
            #alter product
            product = Products.objects.get(id=transaction.product)
            product.quantity_available = product.quantity_available - transaction.quantity
            product.save()

            # alter batch
            batches = Batch.objects.filter(state='Current')
            if lens(batches) == 1:
                batch = batches[0]
                if batch.quantity_remaining > transaction.quantity:
                    batch.quantity_remaining = batch.quantity_remaining - transaction.quantity
                    batch.save()
        else:
            print("form not valid")
            return render(request, template, {
                'form': form,
            })
    else:
        form = TransactionForm()

    return render(request, template, {'form': form})


class TransactionListView(LoginRequiredMixin, ListView):
    model = Transaction                    

templates/inventory/batch_form.html
{% extends 'userinterfacedesign/base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
{% if user.is_authenticated %}
<div class="login-form-area mg-t-30 mg-b-15">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-3"></div>

      <div class="col-lg-6">
        <div class="login-bg">

          <div class="row">
            <div class="col-lg-12">
              <div class="login-title">
                <h1 class='text-center'> New Batch</h1>
              </div>
            </div>
          </div>
          <form id="adminpro-review-form" class="adminpro-form" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="row">
              <div class="col-lg-4"></div>
              <div class="col-lg-8">
                <div class="login-button-pro">
                  <button type="submit" class="login-button login-button-lg">Update</button>
                </div>
              </div>
            </div>
          </form>


        </div>
      </div>
    </div>

  </div>
</div>
</div>
{% endif %}
{% endblock content %}

templates/inventory/batch_list.html
{% extends 'userinterfacedesign/base.html' %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<div class="data-table-area mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="sparkline13-list shadow-reset">
                    <div class="sparkline13-hd">
                        <div class="main-sparkline13-hd">
                            <h1>Projects <span class="table-project-n">Data</span> Table</h1>
                            <div class="sparkline13-outline-icon">
                                <span class="sparkline13-collapse-link"><i class="fa fa-chevron-up"></i></span>
                                <span><i class="fa fa-wrench"></i></span>
                                <span class="sparkline13-collapse-close"><i class="fa fa-times"></i></span>
                            </div>
                        </div>
                    </div>
                    <div class="sparkline13-graph">
                        <div class="datatable-dashv1-list custom-datatable-overright">
                            <div id="toolbar">
                                <select class="form-control">
                                    <option value="">Export Basic</option>
                                    <option value="all">Export All</option>
                                    <option value="selected">Export Selected</option>
                                </select>
                            </div>
                            <table id="table" data-toggle="table" data-pagination="true" data-search="true"
                                data-show-columns="true" data-show-pagination-switch="true" data-show-refresh="true"
                                data-key-events="true" data-show-toggle="true" data-resizable="true" data-cookie="true"
                                data-cookie-id-table="saveId" data-show-export="true" data-click-to-select="true"
                                data-toolbar="#toolbar">
                                <thead>
                                    <tr>
                                        <th data-field="state" data-checkbox="true"></th>
                                        <th data-field="id">ID</th>
                                        <th data-field="date_delivery" data-editable="true">Delivered date</th>
                                        <th data-field="date_expiry" data-editable="true">Expirty date</th>
                                        <th data-field="date_finished" data-editable="true">Date finished</th>
                                        <th data-field="delivered_quantity" data-editable="true">Quantity delivered</th>
                                        <th data-field="quantity_remaining" data-editable="true">Quantity remaining</th>
                                        <th data-field="pallet" data-editable="true">PalletID</th>
                                        <th data-field="product" data-editable="true">ProductID</th>
                                        <th data-field="receiver" data-editable="true">Receiver</th>
                                        <th data-field="supplier" data-editable="true">Supplier</th>
                                        <th data-field="_state" data-editable="true">State</th>

                                    </tr>
                                </thead>

                                {% for batch in batch_list %}




                                <tr>
                                    <td></td>
                                    <td>{{batch.id}}</td>
                                    <td>{{batch.date_delivery}}</td>
                                    <td>{{batch.date_expiry}}</td>
                                    <td>{{batch.date_finished}}</td>
                                    <td>{{batch.delivered_quantity}}</td>
                                    <td>{{batch.quantity_remaining}}</td>
                                    <td>{{batch.pallet}}</td>
                                    <td>{{batch.product}}</td>
                                    <td>{{batch.receiver}}</td>
                                    <td>{{batch.supplier}}</td>
                                    <td>{{batch.state}}</td>




                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Static Table End -->
</div>
</div>




</div>

</div>
{% endif %}
{% endblock content %}

templates/inventory/category_form.html
{% extends 'userinterfacedesign/base.html' %}
{% load static %}
{% block content %}
{% load bootstrap4 %}
{% if user.is_authenticated %}
<div class="login-form-area mg-t-30 mg-b-15">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-3"></div>

      <div class="col-lg-6">
        <div class="login-bg">

          <div class="row">
            <div class="col-lg-12">
              <div class="login-title">
                <h1 class='text-center'> New Category</h1>
              </div>
            </div>
          </div>
          <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="row">
              <div class="col-lg-4"></div>
              <div class="col-lg-8">
                <div class="login-button-pro">
                  <button type="submit" class="login-button login-button-lg">Add</button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>

  </div>
</div>
</div>
{% endif %}
{% endblock content %}

templates/inventory/pallet_form.html
{% extends 'userinterfacedesign/base.html' %}
{% load static %}
{% block content %}
{% load bootstrap4 %}

<div class="login-form-area mg-t-30 mg-b-15">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-3"></div>

      <div class="col-lg-6">
        <div class="login-bg">

          <div class="row">
            <div class="col-lg-12">
              <div class="login-title">
                <h1 class='text-center'> New Pallet</h1>
              </div>
            </div>
          </div>
          <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}

            <div class="row">
              <div class="col-lg-4"></div>
              <div class="col-lg-8">
                <div class="login-button-pro">
                  <button type="submit" class="login-button login-button-lg">Add</button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>

  </div>
</div>
</div>

{% endblock content %}

templates/inventory/pallet_list.html
{% extends 'userinterfacedesign/base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
{% if user.is_authenticated %}
<div class="data-table-area mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="sparkline13-list shadow-reset">
                    <div class="sparkline13-hd">
                        <div class="main-sparkline13-hd">
                            <h1>Available <span class="table-project-n">Warehouse</span> List</h1>
                            <div class="sparkline13-outline-icon">
                                <span class="sparkline13-collapse-link"><i class="fa fa-chevron-up"></i></span>
                                <span><i class="fa fa-wrench"></i></span>
                                <span class="sparkline13-collapse-close"><i class="fa fa-times"></i></span>
                            </div>
                        </div>
                    </div>
                    <div class="sparkline13-graph">
                        <div class="datatable-dashv1-list custom-datatable-overright">
                            <div id="toolbar">
                                <select class="form-control">
                                    <option value="">Export Basic</option>
                                    <option value="all">Export All</option>
                                    <option value="selected">Export Selected</option>
                                </select>
                            </div>
                            <table id="table" data-toggle="table" data-pagination="true" data-search="true"
                                data-show-columns="true" data-show-pagination-switch="true" data-show-refresh="true"
                                data-key-events="true" data-show-toggle="true" data-resizable="true" data-cookie="true"
                                data-cookie-id-table="saveId" data-show-export="true" data-click-to-select="true"
                                data-toolbar="#toolbar">
                                <thead>
                                <tr>
                                        <th data-field="state" data-checkbox="true"></th>
                                        <th data-field="id">ID</th>
                                        <th data-field="warehouse" data-editable="true">Pallet Name</th>
                                        <th data-field="location" data-editable="true">Warehouse</th>
                                        <th> </th>

                                    </tr>
                                                                </thead>


                                       {% for pallet in pallet_list %}

                                        <tr>
                                                                        <td></td>
                                        <td>{{pallet.id}}</td>
<td>{{pallet.name}}</td>
<td>{{pallet.warehouse}}</td>
<td><a href="{% url 'inventory:pallet_detail' pk=pallet.pk %}">Edit</a> </td>


</tr>
{% endfor   %}
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<!-- Static Table End -->
</div>
</div>

<div class="container">
    <h2>Pallets</h2>
    <ul class="list-group">
        {% for pallet in pallet_list %}
        <li class="list-group-item">{{pallet.name}}</li>
        <li class="list-group-item">{{pallet.warehouse}}</li>
        {% comment %} {% if pallet.products%}
        {% for product in pallet.products%}
        <li class="list-group-item">{{product.name}}</li>
        {% endfor %}
        {% endif %} {% endcomment %}

        {% endfor   %}


    </ul>
</div>






{% endif %}
{% endblock content %}

templates/inventory/products_confirm_delete.html
{% extends 'userinterfacedesign/base.html' %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{object}} ?</p>
    <input type="submit" class="btn btn-danger" name="" value="Confirm">
  </form>
{% endblock content %}

templates/inventory/products_detail.html
{% extends 'userinterfacedesign/base.html' %}
{% block content %}

{% if user.is_authenticated %}
<div>
<div id="viewmail" class="tab-pane fade in animated zoomInDown shadow-reset custom-inbox-message">
  <div class="view-mail-wrap ">
    <div class="mail-title">
      <h2 class='text-center'>Product Details</h2>
      <div class="view-mail-action">
        <a href="#"><i class="fa "></i> Cancel</a>
        <a class="compose-draft-bt" href="{% url 'inventory:products_update' pk=products.pk %}"><i class="fa "></i> Edit</a>
        <a class="compose-discard-bt" href="{% url 'inventory:products_delete' pk=products.pk %}"><i class="fa fa-trash-o"></i> Delete</a>
      </div>
    </div>

    <p> {{product.name}} <p>
    <p> Selling Price: {{products.selling_price}}</p>
    <p> Cost Price: {{products.cost_price}}</p>
    <p> Quantity: {{products.quantity}}</p>
    <p> Quantity Available: {{products.quantity_available}}</p>
    <p> Unit Measure: {{products.unit_measure}}</p>
    <p> Reorder Level: {{products.reoder_level}}</p>
    <p> Category: {{products.category}}</p>

    <p> Pallet: {{products.pallet}}



      {% endif %}
</div>
</div>
</div>

      {% endblock content %}

templates/inventory/products_form.html
{% extends 'userinterfacedesign/base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
{% load bootstrap4 %}

<div class="login-form-area mg-t-30 mg-b-15">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-3"></div>

      <div class="col-lg-6">
        <div class="login-bg">

          <div class="row">
            <div class="col-lg-12">
              <div class="login-title">
                <h1 class='text-center'> New Product</h1>
              </div>
            </div>
          </div>
          <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}

            <div class="row">
              <div class="col-lg-4"></div>
              <div class="col-lg-8">
                <div class="login-button-pro">
                  <button type="submit" class="login-button login-button-lg">Add</button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>

  </div>
</div>
</div>
{% endblock content %}