hotel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from accounts import views

from django.contrib.auth import views as auth_views


router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('home/', TemplateView.as_view(template_name='userinterfacedesign/index.html'), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('inventory/', include('inventory.urls', namespace='inventory')),
   


    path('pp/', include('supplier.urls'), name='procurement_portal'),

    ####### API #############################
    # path('', include(router.urls)),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

supplier/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views

from .forms import EmailValidationOnForgotPassword
from . import views

app_name = 'supplier'

urlpatterns = [
    path('', views.index, name='supply_home'),

    url('login/', views.user_login, name='user_login'),
    url('register/', views.register_user, name='register_user'),
    url('logout/', views.loguser_out, name='logout'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),

    path(r'password_reset', auth_views.PasswordResetView.as_view(template_name='supplier/auth/password_reset_form.html',
                                                                 subject_template_name='supplier/auth/password_reset_subject.txt',
                                                                 email_template_name='supplier/auth/password_reset_email.html',
                                                                 form_class=EmailValidationOnForgotPassword), name='password_reset'),
    path(r'reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='supplier/auth/password_reset_confirm.html'), name='password_reset_confirm'),

    # =============================================================================================

    path('tenders/all', views.tenders_all_view, name='all_tenders'),
    path('tenders/<int:pk>', views.tenders_detail_view, name='tender_detail_n_apply'),
# change pass
    path('editprofile/', views.editprofile, name='editprofile'),
    path('changepassword/', views.changepassword, name='changepassword'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

supplier/models.py
from django.db import models

# Create your models here.
from django.utils import timezone

from accounts.models import User
# from inventory.models import Products


class Company(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='company_admin')
    name = models.CharField(max_length=100, default='')
    address = models.CharField(max_length=100, default='')
    phone = models.CharField(max_length=100, default='')
    registered_on = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name


class Tender(models.Model):
    title = models.CharField(max_length=100, default='')
    product = models.ForeignKey('inventory.Products', on_delete=models.CASCADE, related_name='tender_product')
    quantity = models.PositiveIntegerField(default=0)
    opened_on = models.DateField(auto_now_add=True)
    application_deadline = models.DateField(default=timezone.now)
    is_active = models.BooleanField(default=True)
    rating = models.PositiveIntegerField(default=1)
    requirements = models.TextField()


class TenderApplication(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='applicant')
    tender = models.ForeignKey(Tender, on_delete=models.CASCADE, related_name='tender', default=1)
    application_date = models.DateField(auto_now_add=True)
    is_successful = models.BooleanField(default=False)
    discount_terms = models.TextField(default='nill')

supplier/forms.py
from django import forms
from django.contrib.auth.forms import PasswordResetForm, UserCreationForm
from django.core.exceptions import ValidationError

from accounts.models import User
from .models import Company


class EmailValidationOnForgotPassword(PasswordResetForm):
    def clean_email(self):
        email = self.cleaned_data['email']
        if not User.objects.filter(email__iexact=email, is_active=True).exists():
            raise ValidationError("There is no user registered with the specified email address!")
        return email


class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}), max_length=30,
                                 required=True,)
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}), max_length=30,
                                required=True,)
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}), max_length=30,
                               required=True,)
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email Address'}), max_length=254,
                             required=True, help_text='Required. Inform a valid email address.')
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
                                required=True)
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}),
                                required=True)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}), required=True)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
                               required=True)


class ResetForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}), required=True)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                               required=True)
    password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                                      required=True)


class CompanyForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Company Name'}),
                               required=True,)
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address'}),
                               required=True,)
    phone = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Phone Number'}),
                               required=True,)

    class Meta:
        model = Company
        exclude = ('user', 'registered_on',)

supplier/views.py
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib import messages
# Create your views here.
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from accounts.forms import LoginForm, PasswordChangeForm ,UserChangeForm
from accounts.models import User
from .models import Company, Tender, TenderApplication
from .forms import UserRegisterForm, CompanyForm
from .tokens import account_activation_token


def index(request):
    template = 'supplier/index.html'
    tender_list = Tender.objects.filter(is_active=True).order_by('-rating')[:10]
    return render(request, template, {'tenders': tender_list})


# ==================== Auth ======================

def user_login(request):
    template = 'supplier/auth/login.html'
    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            if not User.objects.filter(email=form.cleaned_data['username']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'Username doest not exists.'
                })
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user is not None:
                login(request, user)
                return HttpResponseRedirect('/pp/')
            else:
                return render(request, template, {
                    'form': form
                })
        else:
            return render(request, template, {
                'form': form,
            })
    else:
        form = LoginForm()

    return render(request, template, {'form': form})


def register_user(request):
    template = 'supplier/auth/user_registration.html'
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        form2 = CompanyForm(request.POST)
        if form.is_valid() and form2.is_valid():
            if User.objects.filter(username=form.cleaned_data['username']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'A user with such username already exists.'
                })
            elif User.objects.filter(email=form.cleaned_data['email']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'A user with such email already exists.'
                })
            else:

                # create user
                user = form.save(commit=False)
                user.is_active = False
                user.save()

                # create company
                company = Company()
                company.user = user
                company.name = form2.cleaned_data['name']
                company.address = form2.cleaned_data['address']
                company.phone = form2.cleaned_data['phone']
                company.save()

                # send email address
                current_site = get_current_site(request)
                mail_subject = '( Asyana ) Activate your account.'
                message = render_to_string('supplier/auth/acc_active_email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                })
                to_email = form.cleaned_data.get('email')
                email = EmailMessage(
                    mail_subject, message, to=[to_email]
                )
                email.send()
                return render(request, 'supplier/auth/registration_email_sent.html', {})
        else:
            return render(request, template, {
                'form': form,
                'company_form': form2
            })
        # No post data availabe, let's just show the page.
    else:
        form = UserRegisterForm()
        form2 = CompanyForm(initial={'user': request.user})

    return render(request, template, {'form': form, 'company_form': form2})


def activate(request, uidb64, token):
    template = 'supplier/auth/acc_activate_done.html'
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        return render(request, template,
                      {'message': 'Thank you for your email confirmation. Now you can login your account.'})
    else:
        return render(request, template, {'error': 'Activation link is invalid!'})


def loguser_out(request):
    logout(request)
    return HttpResponseRedirect('/pp/')


# ========================================================================

def tenders_all_view(request):
    template = 'supplier/tenders_all.html'
    tender_list = Tender.objects.filter(is_active=True)
    return render(request, template, tender_list)


def tenders_detail_view(request, pk):
    template = 'supplier/tenders_detail.html'
    user = request.user
    tender = Tender.objects.get(id=pk)
    if request.method == 'POST':  # apply for this tender
        if not request.user.is_authenticated:
            return redirect('/pp/login/')
        my_tender = TenderApplication(user=user, tender=tender, discount_terms=request.POST.get('discount_terms', None))
        my_tender.save()
        return render(request, 'supplier/application_received.html')
    return render(request, template, {'tender': tender})


# supplier change pass word
def editprofile(request):
    if request.method == "POST":
        form = UserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, ("Your Profile Updated"))
            return redirect('home')
    else:
        form = UserChangeForm(instance=request.user)
    context = {'form': form}
    return render(request, 'supplier/editprofile.html', context)


# user password change form

def changepassword(request):
    if request.method == "POST":
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            
            messages.success(request, "Your Password Changed", extra_tags='green')
            return redirect('login')
    else:
        form = PasswordChangeForm(user=request.user)
    context = {'form': form}
    return render(request, 'supplier/changepassword.html', context)

templates/supplier/application_received.html
{% extends "supplier/base.html" %}

{% block content %}
<div class="row col-12 justify-content-center mt-5">
  <div class="col-12 col-md-6">
        <div class="card">
            <div class="card-body">
                    <div class="alert alert-success">
                        <strong>Congratulations. </strong>
                    </div>
                    <p>
                        Your application has been received and is being processed, you will receive an email confirmation of the same.
                        <br><a href="{% url 'supplier:supply_home' %}" class="btn btn-outline-success">OK</a>
                    </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/supplier/base.html
<!doctype html>
<html class="no-js" lang="zxx">
{% include 'supplier/head.html' %}
<body>
{% include 'supplier/topnav.html' %}
{% block content %}


{% endblock content %}
{% include 'supplier/scripts.html' %}
</body>
</html>

templates/supplier/changepassword.html
{% extends 'supplier/base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}

<div class='col-md-2'>
</div>
<div class='col-md-8'>


  <div class="container">
    <div class="form-row">
      <div class="form-group col-md-6">
        <h1>Change Your Password</h1>
        <form method="POST" action="{% url 'accounts:changepassword' %}">
            {% csrf_token %}
            {% if form.errors %}
                <div class="alert alert-warning" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
                <p>Your Form has errors <br> Password Not Changed</p>
                
                </div>
            {% endif %}
            {% bootstrap_form form %}
            
            <input type="submit" value="Change Password" class="btn btn-secondary mb-2">
        </form>
  

      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/supplier/editprofile.html
{% extends 'supplier/base.html' %}
{% load static %}
{% block content %}
{% load bootstrap4 %}
<div class='col-md-2'>
</div>



<div class='col-md-8'>


    <div class="container">
        <div class="form-row">
            <div class="form-group col-md-6">
                <h1 class='text-center'>Edit Your Profile</h1>
                <form class="text-center border border-light p-5" method="POST" action="{% url 'accounts:editprofile' %}">
                    {% csrf_token %}
                    {% if form.errors %}
                    <div class="alert alert-warning" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <p>Your Form has errors <br> Form Not Updated</p>
                    </div>
                    {% endif %}
                    {% bootstrap_form form %}
                    <div class="notification-bt responsive-btn">
                        <input id="basicSuccess" type="submit" value="Change" class="btn btn-success">
                    </div>
                </form>



            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/supplier/head.html
{% load static %}
<head>
     <meta charset="utf-8">
     <meta http-equiv="x-ua-compatible" content="ie=edge">
     <title>Asyana System</title>
     <meta name="description" content="Asyana System Authentication">
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
     <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
     <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
     <!------ Include the above in your HEAD tag ---------->
     <!--===============================================================================================-->
     <link rel="stylesheet" type="text/css" href="{% static 'auth/vendor/bootstrap/css/bootstrap.min.css' %} ">
     <!--===============================================================================================-->
     <link rel="stylesheet" type="text/css" href="{% static 'auth/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %} ">
     <!--===============================================================================================-->
     <link rel="stylesheet" type="text/css" href="{% static 'auth/vendor/animate/animate.css' %} ">
     <!--===============================================================================================-->
     <link rel="stylesheet" type="text/css" href="{% static 'auth/vendor/css-hamburgers/hamburgers.min.css' %} ">
     <!--===============================================================================================-->
     <link rel="stylesheet" type="text/css" href="{% static 'auth/vendor/select2/select2.min.css' %} ">
     <!--===============================================================================================-->
     <link rel="stylesheet" type="text/css" href="{% static 'auth/css/util.css' %} ">
     <link rel="stylesheet" type="text/css" href="{% static 'auth/css/main.css' %} ">
     <link rel="stylesheet" type="text/css" href="{% static 'auth/css/more.css' %} ">
     <link rel="stylesheet" type="text/css" href="{% static 'karumba/css/style.css' %} ">

</head>

templates/supplier/index.html
{% extends 'supplier/base.html' %}
{% load static %}
{% block content %}
<div class="row justify-content-center text-center mt-5">
    <p class="text-center"><b><h3>Welcome to Our <br>Public Procurement Portal</h3></b></p><br>
</div>
<div class="row mt-5">
    <div class="row bg-light justify-content-center col-12 py-5">
        <div class="text-success text-center col-12 col-md-8 col-lg-7 py-4">
            <h3>Top Tenders</h3>
        </div>
        <div class="bg-white col-12 col-md-8 col-lg-7 py-1">
            {% for tender in tenders %}
             <a class="btn btn-block text-left border border-bottom-1" href="{% url 'supplier:tender_detail_n_apply' tender.id %}">
                <span class="tender-color"></span><span>{{tender.title}}</span>
             </a>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

templates/supplier/scripts.html
{% load static %}
<!--===============================================================================================-->
<script src="{% static 'auth/vendor/jquery/jquery-3.2.1.min.js' %} "></script>
<!--===============================================================================================-->
<script src="{% static 'auth/vendor/bootstrap/js/popper.js' %} "></script>
<script src="{% static 'auth/vendor/bootstrap/js/bootstrap.min.js' %} "></script>
<script src="{% static 'karumba/script.js' %} "></script>

templates/supplier/tenders_detail.html
{% extends 'supplier/base.html' %}
{% load static %}
{% block content %}
<div class="row mt-5" >
    <div class="row justify-content-center col-12 py-5">
        <div class="card px-0 col-10 col-md-8 col-lg-5">
            <div class="card-header">{{ tender.title }}</div>
            <div class="card-body">
                <div class="row col-12  p-2" style="border:none; border-bottom:1px solid rgb(200,200,200);">
                    <div class="col-6">Product</div><div class="col-6 text-right"> {{ tender.product }}</div>
                </div>
                <div class="row col-12  p-2" style="border:none; border-bottom:1px solid rgb(200,200,200);">
                    <div class="col-6">Quantity</div><div class="col-6 text-right"> {{ tender.quantity }}</div>
                </div>
                <div class="row col-12  p-2" style="border:none; border-bottom:1px solid rgb(200,200,200);">
                    <div class="col-6">Tender opened</div><div class="col-6 text-right"> {{ tender.opened_on }}</div>
                </div>
                <div class="row col-12  p-2" style="border:none; border-bottom:1px solid rgb(200,200,200);">
                    <div class="col-6">Application deadline</div><div class="col-6 text-right"> {{ tender.application_deadline }}</div>
                </div>
                <div class="row col-12  pt-3">
                    <div class="col-6">Requirements</div><div class="col-6 text-right"> {{ tender.requirements }}</div>
                </div>
                <div class="row col-12  pt-3">
                    <form method="post" action="{% url 'supplier:tender_detail_n_apply' tender.id %}">
                        {% csrf_token %}
                        <div class="container">
                            <div class="row">
                                <div class="col-md-12">
                                    <div data-role="dynamic-fields">
                                        <div class="form-inline">
                                            <div class="form-group">
                                                <label class="sr-only" for="field-name">Field Name</label>
                                                <input type="text" class="form-control" id="field-name" placeholder="Field Name">
                                            </div>
                                            <span>-</span>
                                            <div class="form-group">
                                                <label class="sr-only" for="field-value">Field Value</label>
                                                <input type="text" class="form-control" id="field-value" placeholder="Field Value">
                                            </div>
                                            <button class="btn btn-danger" data-role="remove">
                                                <span class="glyphicon glyphicon-remove"></span>
                                            </button>
                                            <button class="btn btn-primary" data-role="add">
                                                <span class="glyphicon glyphicon-plus"></span>
                                            </button>
                                        </div>  <!-- /div.form-inline -->
                                    </div>  <!-- /div[data-role="dynamic-fields"] -->
                                </div>  <!-- /div.col-md-12 -->
                            </div>  <!-- /div.row -->
                        </div>
                        <textarea placeholder="What are your discount Terms" class="form control form-control-sm col-12" name="discount_terms"></textarea>
                        <button class="btn btn-primary">Apply Now</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/supplier/topnav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03"
    aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand text-success" href="#">Procurement | Portal</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Tenders</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Contracts</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Suppliers</a>
      </li>
    </ul>
    <form class="form-inline mr-auto">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn blue-gradient btn-rounded btn-sm my-0" type="submit">Search</button>
    </form>
    <div class="my-2 my-lg-0">
      {% if request.user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <span class="fa fa-user"></span> {{request.user.username}}
        </a>
        <div class="dropdown-menu" style="left:-50px;" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">My Profile</a>
          <a class="dropdown-item" href="#">More</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'supplier:logout' %}">Logout</a>
        </div>
      </li>
      {% else %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <span class="fa fa-user"></span> Account
        </a>
        <div class="dropdown-menu" style="left:-50px;" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'supplier:user_login' %}">Login</a>
          <a class="dropdown-item" href="{% url 'supplier:register_user' %}">Register</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'supplier:logout' %}">More</a>
        </div>
      </li>
      {% endif %}
    </div>
  </div>
</nav>