accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('', views.profile, name='profile'),

    path(r'password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='supplier/auth/password_reset_done.html'), name='password_reset_done'),
    path(r'reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='supplier/auth/password_reset_complete.html'), name='password_reset_complete'),

    # when user is logged in change password platform
    #path('change-password', views.change_password, name='change_password'),
    path('editprofile/', views.editprofile, name='editprofile'),
    path('changepassword/', views.changepassword, name='changepassword'),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from accounts import views

from django.contrib.auth import views as auth_views


router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('home/', TemplateView.as_view(template_name='userinterfacedesign/index.html'), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('inventory/', include('inventory.urls', namespace='inventory')),
   


    path('pp/', include('supplier.urls'), name='procurement_portal'),

    ####### API #############################
    # path('', include(router.urls)),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.urls import path, include
from . import views

app_name = 'inventory'

urlpatterns = [
    ######################################################################################################
    path('products/', views.ProductsListView.as_view(), name='products_list'),
    path('products/new/', views.ProductsCreateView.as_view(), name='products_new'),
    path('products/detail/<int:pk>/', views.ProductsDetailView.as_view(), name='products_detail'),
    path('products/update/<int:pk>/', views.ProductsUpdateView.as_view(), name='products_update'),
    path('products/delete/<int:pk>/', views.ProductsDeleteView.as_view(), name='products_delete'),
    ##############################################################################################################3
    
      ######################################################################################################
    path('warehouse/', views.WarehouseListView.as_view(), name='warehouse_list'),
    path('warehouse/new/', views.WarehouseCreateView.as_view(), name='warehouse_new'),
    path('warehouse/detail/<int:pk>/', views.WarehouseDetailView.as_view(), name='warehouse_detail'),
    path('warehouse/update/<int:pk>/', views.WarehouseUpdateView.as_view(), name='warehouse_update'),
    path('warehouse/delete/<int:pk>/', views.WarehouseDeleteView.as_view(), name='warehouse_delete'),
    ##############################################################################################################3
      ######################################################################################################
    path('category/', views.CategoryListView.as_view(), name='category_list'),
    path('category/new/', views.CategoryCreateView.as_view(), name='category_new'),
    path('category/detail/<int:pk>/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('category/update/<int:pk>/', views.CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', views.CategoryDeleteView.as_view(), name='category_delete'),
    ##############################################################################################################3
      ######################################################################################################
    path('pallet/', views.PalletListView.as_view(), name='pallet_list'),
    path('pallet/new/', views.PalletCreateView.as_view(), name='pallet_new'),
    path('pallet/detail/<int:pk>/', views.PalletDetailView.as_view(), name='pallet_detail'),
    path('pallet/update/<int:pk>/', views.PalletUpdateView.as_view(), name='pallet_update'),
    path('pallet/delete/<int:pk>/', views.PalletDeleteView.as_view(), name='pallet_delete'),
    ##############################################################################################################3
    ##############################################################################################################
    path('batch/', views.BatchListView.as_view(), name='batch_list'),
    path('batch/new/', views.BatchCreateView.as_view(), name='batch_new'),
    ##############################################################################################################
    path('transaction/', views.TransactionListView.as_view(), name='transaction_list'),
    path('transaction/new/', views.transaction_create_view, name='transaction_new'),
  ]

templates/userinterfacedesign/base.html
<!doctype html>

{% if user.is_authenticated %}
<html class="no-js" lang="zxx">
{% include 'userinterfacedesign/head.html' %}
{% include 'userinterfacedesign/leftsidebar.html' %}
{% include 'userinterfacedesign/topnav.html' %}
{% include 'userinterfacedesign/mobilemenu.html' %}

{% block content %}


{% endblock content %}



{% include 'userinterfacedesign/footer.html' %}
{% include 'userinterfacedesign/scripts.html' %}

{% endif %}
</html>

templates/userinterfacedesign/footer.html
      </div>
    </div>
  
  <!-- Footer Start-->

    <div class="footer-copyright-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer-copy-right">
                        <p>Copyright &#169; 2020 Colorlib All rights reserved. ERP System by <a href="#">Exergy Technologies</a>.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
   
    <!-- Footer End-->

<!-- Chat Box Start-->
    <div class="chat-list-wrap">
        <div class="chat-list-adminpro">
            <div class="chat-button">
                <span data-toggle="collapse" data-target="#chat" class="chat-icon-link"><i class="fa fa-comments"></i></span>
            </div>
            <div id="chat" class="collapse chat-box-wrap shadow-reset animated zoomInLeft">
                <div class="chat-main-list">
                    <div class="chat-heading">
                        <h2>Messanger</h2>
                    </div>
                    
                    
                    <div class="chat-content chat-scrollbar">
                
                        <div class="author-chat">
                            <h3>Monica <span class="chat-date">10:15 am</span></h3>
                            <p>Hi, what you are doing and where are you gay?</p>
                        </div>
                        <div class="client-chat">
                            <h3>{{request.user.username}} <span class="chat-date">10:10 am</span></h3>
                            <p>Now working in graphic design with coding and you?</p>
                        </div>
                        <div class="author-chat">
                            <h3>Monica <span class="chat-date">10:05 am</span></h3>
                            <p>Practice in programming</p>
                        </div>
                        <div class="client-chat">
                            <h3>Mamun <span class="chat-date">10:02 am</span></h3>
                            <p>That's good man! carry on...</p>
                        </div>
                    </div>
                    <div class="chat-send">
                        <input type="text" placeholder="Type..." />
                        <span><button type="submit">Send</button></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Chat Box End-->

templates/userinterfacedesign/leftsidebar.html
{% load static %}
{% load has_group %}

<body class="materialdesign">
    <!--[if lt IE 8]>
      <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
      <![endif]-->
    <!-- Header top area start-->

    <div class="wrapper-pro">
        <div class="left-sidebar-pro">
            <nav id="sidebar">
                <div class="sidebar-header">
                    <a href="#"><img src="{% static 'userinterfacedesign/img/message/1.jpg ' %}" alt="" />
                    </a>
                    <h3>{{request.user.username}}</h3>
                    <p>{{request.user.groups}}</p>
                    <strong>AP+</strong>
                </div>
                <div class="left-custom-menu-adp-wrap">
                    <ul class="nav navbar-nav left-sidebar-menu-pro">
                        <li class="nav-item">
                            <a href="#" data-toggle="dropdown" role="button" aria-expanded="false"
                                class="nav-link dropdown-toggle"><i class="fa big-icon fa-home"></i> <span
                                    class="mini-dn">Home</span> <span class="indicator-right-menu mini-dn"><i
                                        class="fa indicator-mn fa-angle-left"></i></span></a>
                            <div role="menu" class="dropdown-menu left-menu-dropdown animated flipInX">
                                <a href="{% url 'home' %}" class="dropdown-item">Dashboard </a>
                                <a href="" class="dropdown-item">Point of Sale</a>
                                <a href="" class="dropdown-item">Reports</a>

                            </div>
                        </li>
                    
                            <li class="nav-item"><a href="#" data-toggle="dropdown" role="button" aria-expanded="false"
                                    class="nav-link dropdown-toggle"><i class="fa big-icon fa-building"></i> <span
                                        class="mini-dn">Warehouse</span> <span class="indicator-right-menu mini-dn"><i
                                            class="fa indicator-mn fa-angle-left"></i></span></a>
                                <div role="menu" class="dropdown-menu left-menu-dropdown animated flipInX">
                                    <a href="{% url 'inventory:warehouse_list' %}" class="dropdown-item">View
                                        Warehouse</a>
                                    <a href="{% url 'inventory:pallet_new' %}" class="dropdown-item">View Pallets</a>
                                    <a href="{% url 'inventory:warehouse_new' %}" class="dropdown-item">Add
                                        Warehouse</a>
                                    <a href="{% url 'inventory:pallet_new' %}" class="dropdown-item">Add Pallets</a>

                                    <a href="#" class="dropdown-item">Requisitions</a>
                                    <a href="#" class="dropdown-item">summary</a>
                                </div>
                            </li>
                            <li class="nav-item"><a href="#" data-toggle="dropdown" role="button" aria-expanded="false"
                                    class="nav-link dropdown-toggle"><i class="fa fa-shopping-bag"></i> <span
                                        class="mini-dn">Inventory</span> <span class="indicator-right-menu mini-dn"><i
                                            class="fa indicator-mn fa-angle-left"></i></span></a>
                                <div role="menu" class="dropdown-menu left-menu-dropdown animated flipInX">
                                    <a href="{% url 'inventory:category_list' %}" class="dropdown-item"> Categories</a>
                                    <a href="{% url 'inventory:category_new' %}" class="dropdown-item">New
                                        Categories</a>
                                    <a href="{% url 'inventory:products_list' %}" class="dropdown-item">View
                                        Inventorty</a>
                                    <a href="{% url 'inventory:products_new' %}" class="dropdown-item">Add
                                        Inventorty</a>
                                    <a href="#" class="dropdown-item">Batch Report</a>

                        <li class="nav-item"><a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle"><i class="fa big-icon fa-envelope"></i> <span class="mini-dn">Mailbox</span> <span class="indicator-right-menu mini-dn"><i class="fa indicator-mn fa-angle-left"></i></span></a>
                            <div role="menu" class="dropdown-menu left-menu-dropdown animated flipInX">
                                <a href="inbox.html" class="dropdown-item">Inbox</a>
                                <a href="view-mail.html" class="dropdown-item">View Mail</a>
                                <a href="compose-mail.html" class="dropdown-item">Compose Mail</a>
                            </div>
                        </li>
                         <li class="nav-item"><a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle"><i class="big-icon glyphicon glyphicon-phone-alt"></i> <span class="mini-dn">Help Desk</span> <span class="indicator-right-menu mini-dn"><i class="fa indicator-mn fa-angle-left"></i></span></a>
                            <div role="menu" class="dropdown-menu left-menu-dropdown animated flipInX">
                                <a href="static-table.html" class="dropdown-item">Seek Clarification</a>
                                <a href="data-table.html" class="dropdown-item">Report bugs</a>
                                <a href="data-table.html" class="dropdown-item">Issue Recommendations</a>
                            </div>
                        </li>
                        <li class="nav-item"><a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle"><i class="glyphicon glyphicon-cog"></i> <span class="mini-dn">Profile</span> <span class="indicator-right-menu mini-dn"><i class="fa indicator-mn fa-angle-left"></i></span></a>
                            <div role="menu" class="dropdown-menu left-menu-dropdown animated flipInX">
                                <a href="{% url 'accounts:profile'%}" class="dropdown-item">View Profile</a>
                                <a href="{% url 'accounts:editprofile'%}" class="dropdown-item">Update Profile</a>
                               
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>

templates/userinterfacedesign/profile.html
{% extends 'userinterfacedesign/base.html' %}
{% load static %}
{% block content %}

{% if user.is_authenticated %}



 <div class="project-details-area mg-b-15">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                            <div class="project-details-wrap shadow-reset">
                                <div class="row">
                                    <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
                                        <div class="project-details-title">
                                            <h2><span class="profile-details-name-nn">Contract with</span> Uttara It Park</h2>
                                        </div>
                                        <ul id="adminpro-demo2" class="comment-action-st collapse">
                                            <li><a href="{% url 'accounts:editprofile'%}">Edit</a>
                                            </li>
                                            <li><a href="{% url 'accounts:changepassword'%}">Change Password</a>
                                            </li>
                                            <li><a href="{% url 'home'%}">Cancel</a>
                                            </li>
                                            
                                        </ul>
                                    </div>
                                    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
                                        <div class="admin-comment-month project-details-action">
                                            <button class="comment-setting" data-toggle="collapse" data-target="#adminpro-demo2">...</button>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="project-details-mg">
                                            <div class="row">
                                                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                                    <div class="project-details-st">
                                                        <span><strong>Status:</strong></span>
                                                    </div>
                                                </div>
                                                {% if user.is_active %}
                                                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                                                    <div class="btn-group project-list-ad">
                                                        <button class="btn btn-white btn-xs">Active</button>
                                                    </div>
                                                </div>
                                                
                                                {% endif %}

                                            </div>
                                        </div>
                                        <div class="project-details-mg">
                                            <div class="row">
                                                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                                    <div class="project-details-st">
                                                        <span><strong>Username:</strong></span>
                                                    </div>
                                                </div>
                                                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                                                    <div class="project-details-dt">
                                                        <span>{{user.username}}</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        
                                        <div class="project-details-mg">
                                            <div class="row">
                                                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                                    <div class="project-details-st">
                                                        <span><strong>Email:</strong></span>
                                                    </div>
                                                </div>
                                                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                                                    <div class="project-details-dt">
                                                        <span>{{user.email}}</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="project-details-mg">
                                            <div class="row">
                                                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                                    <div class="project-details-st">
                                                        <span><strong>Names:</strong></span>
                                                    </div>
                                                </div>
                                                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                                                    <div class="project-details-dt">
                                                        <span>{{user.first_name}}  &nbsp; {{user.last_name}}</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="project-details-mg">
                                            <div class="row">
                                                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                                    <div class="project-details-st">
                                                        <span><strong>Departnment</strong></span>
                                                    </div>
                                                </div>
                                                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                                                    <div class="project-details-dt">
                                                        <a href="#">{{user.groups}}</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="project-details-mg">
                                            <div class="row">
                                                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                                    <div class="project-details-st">
                                                        <span><strong>Date Joined</strong></span>
                                                    </div>
                                                </div>
                                                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                                                    <div class="project-details-dt">
                                                        <span>{{user.date_joined}}</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="project-details-mg">
                                            <div class="row">
                                                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                                    <div class="project-details-st">
                                                        <span><strong>Last login</strong></span>
                                                    </div>
                                                </div>
                                                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                                                    <div class="project-details-dt">
                                                        <span>{{user.last_login}}</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="project-details-mg">
                                            <div class="row">
                                                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                                    <div class="project-details-st">
                                                        <span><strong>Departnment Head</strong></span>
                                                    </div>
                                                </div>
                                                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                                                    <div class="project-details-dt">
                                                        <span>Departnment Head</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="project-details-mg">
                                            <div class="row">
                                                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                                    <div class="project-details-st">
                                                        <span><strong>Phone:</strong></span>
                                                    </div>
                                                </div>
                                                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                                                    <div class="project-details-dt">
                                                        <span>{{user.phone}}</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-2">
                                        <div class="project-pregress-details">
                                            <span><strong>Completed:</strong></span>
                                        </div>
                                    </div>
                                    <div class="col-lg-10">
                                        <div class="skill-content-3 project-details-progress">
                                            <div class="skill">
                                                <div class="progress">
                                                    <div class="progress-bar wow fadeInLeft" data-progress="95%" style="width: 95%;" data-wow-duration="10.5s" data-wow-delay="10.2s"> <span>95%</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endif %}
{% endblock content %}